name: currencies_updated
description: The fundamental package for handling currencies with Dart.
version: 0.1.1
homepage: https://github.com/ismaelJimenez/finance

environment:
  sdk: ">=2.12.0 <3.10.0"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  mockito: ^5.4.2
  pedantic: ^1.8.0+1
  test: '>=1.16.6 <=1.24.3'
